### ISSUE TITLE
Environment `PongNoFrameskip` doesn't exist

### ISSUE THREAD

**Issue by ParisaO** [schroederdewitt/meme#4]
Hi,

When I try to run the commands for 'Train Pong MaxEnt' and the 'Train Pong MaxEnt (Restricted Action Space)', I am getting this error and I don't know how to solve this:

```
Traceback (most recent call last):
  File "/content/meme/src/train_ff.py", line 96, in <module>
    vec_env = DummyVecEnv(env_fn=make_env_fn, batch_size=args.bs_rollout)
  File "/content/meme/src/envs.py", line 408, in __init__
    self.envs = [env_fn.x() if isinstance(env_fn, CloudpickleWrapper) else env_fn() for _ in range(batch_size)]
  File "/content/meme/src/envs.py", line 408, in <listcomp>
    self.envs = [env_fn.x() if isinstance(env_fn, CloudpickleWrapper) else env_fn() for _ in range(batch_size)]
  File "/content/meme/src/envs.py", line 724, in _make_env_fn
    env = env_registry[env_tag]()
  File "/content/meme/src/envs.py", line 18, in __init__
    self.reset()
  File "/content/meme/src/envs.py", line 32, in reset
    self.env = make_atari_env('PongNoFrameskip-v4', n_envs=1,
  File "/content/meme/src/sb3/common/env_util.py", line 158, in make_atari_env
    return make_vec_env(
  File "/content/meme/src/sb3/common/env_util.py", line 125, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/content/meme/src/sb3/common/vec_env/dummy_vec_env.py", line 30, in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/content/meme/src/sb3/common/vec_env/dummy_vec_env.py", line 30, in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "/content/meme/src/sb3/common/env_util.py", line 95, in _init
    env = gym.make(env_id, **kwargs)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 740, in make
    env_spec = _find_spec(id)
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 537, in _find_spec
    _check_version_exists(ns, name, version)
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 403, in _check_version_exists
    _check_name_exists(ns, name)
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 380, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `PongNoFrameskip` doesn't exist.
```

**Comment by ParisaO** [comment]
The issue solved by adding this :
```
!pip install -U gym
!pip install "gym[atari, accept-rom-license]"
!pip install -U gymnasium
!pip install "gymnasium[atari, accept-rom-license]"
```
